[tool.poetry]
name = "sdss-clu"
version = "0.1.10"
description = "A new protocol for SDSS actors."
authors = ["José Sánchez-Gallego <gallegoj@uw.edu>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/sdss/clu"
repository = "https://github.com/sdss/clu"
documentation = "https://clu.readthedocs.io/en/latest/"
keywords = ["astronomy", "software"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "clu", from = "python" }
]
include = ["README.md"]
exclude = ["python/clu/tests/*"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.15.1"
"ruamel.yaml" = "^0.15.61"
pygments = "^2.2.0"
Click = "^7.0"
aio_pika = "^6.4.1"
jsonschema = "^3.0.1"
prompt-toolkit = "^3.0.0"

# Docs extras. Need to be added to dependencies and not to dev-dependencies because otherwise
# they won't be installed on pip install .[docs]
# See https://github.com/sdispater/poetry/pull/606#issuecomment-437943927
# Need to do poetry install -E docs to actually install everything.
Sphinx = {version = "^2.0", optional = true}
sphinxcontrib-trio = {version = "1.1.0", optional = true}
semantic-version = {version = "2.8.0", optional = true}
asynctest = {version = "^0.13.0", optional = true}

[tool.poetry.dev-dependencies]
ipython = "^7.9.0"
matplotlib = "^3.1.1"
invoke = "^1.3.0"
flake8 = "^3.7.9"
doc8 = "^0.8.0"
pytest = "^5.2.2"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.8.1"
pytest-sugar = "^0.9.2"
coveralls = "^1.8.2"
toml = "^0.10.0"

[tool.poetry.extras]
docs = ["Sphinx", "sphinxcontrib-trio", "semantic-version", "asynctest"]

[tool.isort]
line_length = 79
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_first_party = "clu"
multi_line_output = 0
balanced_wrapping = true
include_trailing_comma = false
length_sort_stdlib = false
lines_after_imports = 2
# use_parentheses = true

[tool.flake8]
ignore = [
    "H101",
    "N",
    "W504",
]
max-line-length = 99

[build-system]
build-backend = "setuptools.build_meta:__legacy__"
requires = ["setuptools"]
